"""
Finding Generator Engine for StrixSec.
"""

from __future__ import annotations

from datetime import UTC, datetime

from strixsec.assessment.models import AssessmentResult
from strixsec.findings.models import (
    Evidence,
    Finding,
    FindingCategory,
    FindingStatus,
    SeverityLevel,
)


def generate_findings_from_assessment(result: AssessmentResult) -> list[Finding]:
    """Convert AssessmentResult into structured Finding models.

    Args:
        result: AssessmentResult model from Phase 4 assessment subsystem.

    Returns:
        List of generated Finding models.
    """
    findings: list[Finding] = []
    now_utc = datetime.now(UTC).isoformat()
    asset = result.target

    # 1. Security Headers Evaluation
    if result.headers_result:
        for check in result.headers_result.checks:
            if not check.is_present:
                sev, title, impact = _get_header_issue_meta(check.header_name)
                evidence_item = Evidence(
                    type="Security Header",
                    source=result.target,
                    description=f"Security header '{check.header_name}' was not found in response.",
                    sanitized_value=f"Header '{check.header_name}': MISSING",
                    timestamp=now_utc,
                )

                findings.append(
                    Finding(
                        id="",  # Auto-generated by storage if blank
                        title=title,
                        asset=asset,
                        category=FindingCategory.SECURITY_HEADER,
                        severity=sev,
                        confidence="HIGH",
                        description=check.implication,
                        evidence=[evidence_item],
                        impact=impact,
                        remediation=check.recommendation,
                        references=["https://owasp.org/www-project-secure-headers/"],
                        status=FindingStatus.OPEN,
                        created_at=now_utc,
                        updated_at=now_utc,
                    )
                )

    # 2. TLS Assessment
    if result.tls_result:
        tls = result.tls_result
        if tls.cert_info:
            if tls.cert_info.is_expired:
                evidence_item = Evidence(
                    type="TLS Certificate",
                    source=asset,
                    description="TLS certificate is expired.",
                    sanitized_value=f"Valid To: {tls.cert_info.valid_to}",
                    timestamp=now_utc,
                )
                findings.append(
                    Finding(
                        id="",
                        title="Expired TLS Certificate",
                        asset=asset,
                        category=FindingCategory.TLS,
                        severity=SeverityLevel.HIGH,
                        confidence="HIGH",
                        description="The target's TLS certificate has passed its expiration date.",
                        evidence=[evidence_item],
                        impact=(
                            "Browsers will display severe security warnings and reject connections."
                        ),
                        remediation=(
                            "Renew and install a valid TLS certificate from a "
                            "trusted Certificate Authority."
                        ),
                        references=[],
                        status=FindingStatus.OPEN,
                        created_at=now_utc,
                        updated_at=now_utc,
                    )
                )

            if not tls.cert_info.hostname_matches:
                evidence_item = Evidence(
                    type="TLS Certificate",
                    source=asset,
                    description="Certificate CN/SAN does not match target hostname.",
                    sanitized_value=f"Target: {asset}, SANs: {tls.cert_info.sans}",
                    timestamp=now_utc,
                )
                findings.append(
                    Finding(
                        id="",
                        title="TLS Certificate Hostname Mismatch",
                        asset=asset,
                        category=FindingCategory.TLS,
                        severity=SeverityLevel.HIGH,
                        confidence="HIGH",
                        description=(
                            "The TLS certificate presented does not match the target domain name."
                        ),
                        evidence=[evidence_item],
                        impact=(
                            "Clients cannot verify server identity, enabling "
                            "man-in-the-middle impersonation."
                        ),
                        remediation=(
                            "Reissue certificate ensuring target hostname is included "
                            "in Subject Alternative Names (SANs)."
                        ),
                        references=[],
                        status=FindingStatus.OPEN,
                        created_at=now_utc,
                        updated_at=now_utc,
                    )
                )
        elif tls.status != "SUCCESS":
            evidence_item = Evidence(
                type="TLS Inspection",
                source=asset,
                description=f"TLS check failed: {tls.error}",
                sanitized_value=f"TLS Status: {tls.status}, Error: {tls.error}",
                timestamp=now_utc,
            )
            findings.append(
                Finding(
                    id="",
                    title=f"TLS Configuration Issue: {tls.status}",
                    asset=asset,
                    category=FindingCategory.TLS,
                    severity=SeverityLevel.MEDIUM,
                    confidence="HIGH",
                    description=f"TLS handshake or certificate check failed for {asset}.",
                    evidence=[evidence_item],
                    impact="Secure encrypted communication cannot be established cleanly.",
                    remediation=(
                        "Verify server TLS configuration and ensure valid "
                        "certificates are configured."
                    ),
                    references=[],
                    status=FindingStatus.OPEN,
                    created_at=now_utc,
                    updated_at=now_utc,
                )
            )

    # 3. Cookie Security Analysis
    if result.cookie_result:
        for c in result.cookie_result.cookies:
            if not c.secure:
                evidence_item = Evidence(
                    type="Cookie Security",
                    source=c.cookie_name,
                    description=f"Cookie '{c.cookie_name}' is missing the Secure attribute.",
                    sanitized_value=c.redacted_header,
                    timestamp=now_utc,
                )
                findings.append(
                    Finding(
                        id="",
                        title=f"Cookie Missing Secure Flag: {c.cookie_name}",
                        asset=asset,
                        category=FindingCategory.COOKIE,
                        severity=SeverityLevel.MEDIUM,
                        confidence="HIGH",
                        description=(
                            f"The cookie '{c.cookie_name}' was set without the 'Secure' flag."
                        ),
                        evidence=[evidence_item],
                        impact=(
                            "Cookie may be transmitted over unencrypted HTTP, "
                            "exposing it to network eavesdropping."
                        ),
                        remediation=(
                            f"Append the 'Secure' flag to the Set-Cookie "
                            f"directive for '{c.cookie_name}'."
                        ),
                        references=[],
                        status=FindingStatus.OPEN,
                        created_at=now_utc,
                        updated_at=now_utc,
                    )
                )

            if not c.httponly:
                evidence_item = Evidence(
                    type="Cookie Security",
                    source=c.cookie_name,
                    description=f"Cookie '{c.cookie_name}' is missing the HttpOnly attribute.",
                    sanitized_value=c.redacted_header,
                    timestamp=now_utc,
                )
                findings.append(
                    Finding(
                        id="",
                        title=f"Cookie Missing HttpOnly Flag: {c.cookie_name}",
                        asset=asset,
                        category=FindingCategory.COOKIE,
                        severity=SeverityLevel.MEDIUM,
                        confidence="HIGH",
                        description=(
                            f"The cookie '{c.cookie_name}' was set without the 'HttpOnly' flag."
                        ),
                        evidence=[evidence_item],
                        impact=(
                            "Client-side scripts can access cookie value via "
                            "document.cookie, increasing XSS risk."
                        ),
                        remediation=(
                            f"Append the 'HttpOnly' flag to the Set-Cookie "
                            f"directive for '{c.cookie_name}'."
                        ),
                        references=[],
                        status=FindingStatus.OPEN,
                        created_at=now_utc,
                        updated_at=now_utc,
                    )
                )

    # 4. Public Security Metadata
    if result.metadata_result:
        meta = result.metadata_result
        if meta.security_txt_found and meta.security_txt_content:
            evidence_item = Evidence(
                type="Public Metadata",
                source="security.txt",
                description="Public security policy file security.txt is present.",
                sanitized_value=meta.security_txt_content[:200],
                timestamp=now_utc,
            )
            findings.append(
                Finding(
                    id="",
                    title="Public Security Contact Policy Discovered (security.txt)",
                    asset=asset,
                    category=FindingCategory.METADATA,
                    severity=SeverityLevel.INFO,
                    confidence="HIGH",
                    description="Target publishes a security contact policy via security.txt.",
                    evidence=[evidence_item],
                    impact="Informational finding detailing security disclosure channel.",
                    remediation="Maintain security.txt contact information up to date.",
                    references=["https://securitytxt.org/"],
                    status=FindingStatus.OPEN,
                    created_at=now_utc,
                    updated_at=now_utc,
                )
            )

    return findings


def _get_header_issue_meta(header_name: str) -> tuple[SeverityLevel, str, str]:
    """Map missing header names to conservative severity ratings, titles, and impacts."""
    mapping = {
        "Strict-Transport-Security": (
            SeverityLevel.MEDIUM,
            "Missing Strict-Transport-Security (HSTS) Header",
            "Clients may connect over unencrypted HTTP, allowing network eavesdropping.",
        ),
        "Content-Security-Policy": (
            SeverityLevel.MEDIUM,
            "Missing Content-Security-Policy (CSP) Header",
            "Increased susceptibility to Cross-Site Scripting (XSS) and data injection.",
        ),
        "X-Content-Type-Options": (
            SeverityLevel.LOW,
            "Missing X-Content-Type-Options Header",
            "Browsers may perform MIME-sniffing and execute unexpected file payloads.",
        ),
        "X-Frame-Options": (
            SeverityLevel.LOW,
            "Missing X-Frame-Options Header",
            "Page may be embedded in malicious iframes, enabling Clickjacking attacks.",
        ),
        "Referrer-Policy": (
            SeverityLevel.INFO,
            "Missing Referrer-Policy Header",
            "Sensitive URL path information may leak in Referer headers to external origins.",
        ),
        "Permissions-Policy": (
            SeverityLevel.INFO,
            "Missing Permissions-Policy Header",
            "Unrestricted access to browser hardware features and APIs.",
        ),
    }
    return mapping.get(
        header_name,
        (
            SeverityLevel.INFO,
            f"Missing Security Header: {header_name}",
            "Security header is missing from HTTP response.",
        ),
    )
