"""
Safe HTML Report Renderer for StrixSec.
"""

from __future__ import annotations

import html

from strixsec.findings.models import SeverityLevel
from strixsec.reporting.models import ReportContext

# Severity badge CSS colors
_SEVERITY_COLORS: dict[str, str] = {
    SeverityLevel.CRITICAL: "#c0392b",
    SeverityLevel.HIGH: "#e67e22",
    SeverityLevel.MEDIUM: "#f1c40f",
    SeverityLevel.LOW: "#2980b9",
    SeverityLevel.INFO: "#7f8c8d",
}

_CSS = """
<style>
  body { font-family: Arial, sans-serif; margin: 0; padding: 0;
         background: #f4f6f8; color: #2c3e50; }
  header { background: #1a252f; color: #ecf0f1; padding: 32px 40px; }
  header h1 { margin: 0 0 8px; font-size: 28px; }
  header p { margin: 0; opacity: 0.7; font-size: 14px; }
  main { max-width: 960px; margin: 32px auto; padding: 0 24px 64px; }
  h2 { border-bottom: 2px solid #dde1e6; padding-bottom: 8px;
       margin-top: 40px; font-size: 20px; }
  .meta-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px;
               background: #fff; border: 1px solid #dde1e6; border-radius: 6px;
               padding: 20px; margin-bottom: 24px; }
  .meta-item label { font-weight: bold; font-size: 12px;
                     text-transform: uppercase; color: #7f8c8d; }
  .meta-item p { margin: 4px 0 0; font-size: 14px; }
  .exec-summary { background: #fff; border-left: 4px solid #2980b9;
                  padding: 16px 20px; border-radius: 4px;
                  font-size: 15px; line-height: 1.6; }
  .sev-table { width: 100%; border-collapse: collapse;
               background: #fff; border-radius: 6px; overflow: hidden; }
  .sev-table th, .sev-table td { padding: 12px 16px; text-align: left;
                                  border-bottom: 1px solid #eee; font-size: 14px; }
  .sev-table th { background: #f4f6f8; font-weight: bold; }
  .badge { display: inline-block; padding: 3px 10px; border-radius: 12px;
           color: #fff; font-size: 12px; font-weight: bold; }
  .finding-card { background: #fff; border: 1px solid #dde1e6;
                  border-radius: 6px; margin-bottom: 20px;
                  border-left: 4px solid #bdc3c7; }
  .finding-header { padding: 16px 20px; border-bottom: 1px solid #eee;
                    display: flex; align-items: center; gap: 12px; }
  .finding-id { font-family: monospace; font-size: 13px;
                background: #ecf0f1; padding: 2px 8px; border-radius: 4px; }
  .finding-title { font-size: 16px; font-weight: bold; flex: 1; }
  .finding-body { padding: 16px 20px; }
  .field-row { margin-bottom: 12px; }
  .field-label { font-size: 12px; font-weight: bold; text-transform: uppercase;
                 color: #7f8c8d; margin-bottom: 4px; }
  .field-value { font-size: 14px; line-height: 1.5; }
  .evidence-block { background: #f4f6f8; padding: 10px 14px;
                    border-radius: 4px; font-family: monospace; font-size: 13px;
                    white-space: pre-wrap; word-break: break-all; }
  .scan-table { width: 100%; border-collapse: collapse;
                background: #fff; border-radius: 6px; overflow: hidden; }
  .scan-table th, .scan-table td { padding: 10px 16px; text-align: left;
                                    border-bottom: 1px solid #eee; font-size: 13px; }
  .scan-table th { background: #f4f6f8; font-weight: bold; }
  footer { text-align: center; font-size: 12px; color: #95a5a6;
           padding: 24px; }
</style>
"""


def _esc(value: str | None) -> str:
    """Safely HTML-escape a string value."""
    if value is None:
        return ""
    return html.escape(str(value), quote=True)


def _badge(severity: str) -> str:
    """Return HTML severity badge string with safely escaped content."""
    sev_upper = str(severity).upper()
    color = _SEVERITY_COLORS.get(sev_upper, "#7f8c8d")
    return f'<span class="badge" style="background:{color}">{_esc(severity)}</span>'


def render_html(ctx: ReportContext) -> str:
    """Render a complete, self-contained HTML report from a ReportContext.

    Args:
        ctx: Assembled ReportContext from ReportBuilder.

    Returns:
        Complete HTML document as a string.
    """
    meta = ctx.metadata
    sev = ctx.severity_summary

    # --- Header ---
    header = f"""
    <header>
      <h1>{_esc(meta.title)}</h1>
      <p>Generated by StrixSec v{_esc(meta.strixsec_version)} &mdash; {_esc(meta.generated_at)}</p>
    </header>"""

    # --- Metadata Grid ---
    scope_str = _esc(", ".join(meta.scope)) if meta.scope else "Not specified"
    assets_str = _esc(", ".join(meta.assets)) if meta.assets else "None"
    meta_grid = f"""
    <div class="meta-grid">
      <div class="meta-item"><label>Assessment Title</label>
        <p>{_esc(meta.title)}</p></div>
      <div class="meta-item"><label>StrixSec Version</label>
        <p>v{_esc(meta.strixsec_version)}</p></div>
      <div class="meta-item"><label>Generated At</label>
        <p>{_esc(meta.generated_at)}</p></div>
      <div class="meta-item"><label>Total Findings</label>
        <p>{sev.total}</p></div>
      <div class="meta-item"><label>Scope</label><p>{scope_str}</p></div>
      <div class="meta-item"><label>Assets Assessed</label>
        <p>{assets_str}</p></div>
    </div>"""

    # --- Executive Summary ---
    exec_section = f"""
    <h2>Executive Summary</h2>
    <div class="exec-summary">{_esc(ctx.executive_summary)}</div>"""

    # --- Severity Summary Table ---
    sev_rows = ""
    sev_map = [
        ("CRITICAL", sev.critical, "#c0392b"),
        ("HIGH", sev.high, "#e67e22"),
        ("MEDIUM", sev.medium, "#f1c40f"),
        ("LOW", sev.low, "#2980b9"),
        ("INFORMATIONAL", sev.informational, "#7f8c8d"),
    ]
    for label, count, color in sev_map:
        sev_rows += f"""
        <tr>
          <td><span class="badge" style="background:{color}">{label}</span></td>
          <td>{count}</td>
        </tr>"""

    sev_section = f"""
    <h2>Severity Summary</h2>
    <table class="sev-table">
      <thead><tr><th>Severity</th><th>Count</th></tr></thead>
      <tbody>{sev_rows}
        <tr style="font-weight:bold"><td>TOTAL</td><td>{sev.total}</td></tr>
      </tbody>
    </table>"""

    # --- Findings ---
    if ctx.findings:
        finding_cards = ""
        for f in ctx.findings:
            ev_html = ""
            for ev in f.evidence:
                ev_html += f"""
            <div class="field-row">
              <div class="field-label">Evidence — {_esc(ev.type)} / {_esc(ev.source)}</div>
              <div class="evidence-block">{_esc(ev.sanitized_value)}</div>
            </div>"""

            refs_html = ""
            for ref in f.references:
                refs_html += f'<div><a href="{_esc(ref)}">{_esc(ref)}</a></div>'

            finding_cards += f"""
        <div class="finding-card">
          <div class="finding-header">
            <span class="finding-id">{_esc(f.id)}</span>
            <span class="finding-title">{_esc(f.title)}</span>
            {_badge(str(f.severity))}
          </div>
          <div class="finding-body">
            <div class="field-row">
              <div class="field-label">Category</div>
              <div class="field-value">{_esc(str(f.category))}</div>
            </div>
            <div class="field-row">
              <div class="field-label">Asset</div>
              <div class="field-value">{_esc(f.asset)}</div>
            </div>
            <div class="field-row">
              <div class="field-label">Confidence</div>
              <div class="field-value">{_esc(f.confidence)}</div>
            </div>
            <div class="field-row">
              <div class="field-label">Status</div>
              <div class="field-value">{_esc(str(f.status))}</div>
            </div>
            <div class="field-row">
              <div class="field-label">Description</div>
              <div class="field-value">{_esc(f.description)}</div>
            </div>
            {ev_html}
            <div class="field-row">
              <div class="field-label">Impact</div>
              <div class="field-value">{_esc(f.impact)}</div>
            </div>
            <div class="field-row">
              <div class="field-label">Remediation</div>
              <div class="field-value">
                {_esc(f.remediation or "N/A")}
              </div>
            </div>
            <div class="field-row">
              <div class="field-label">References</div>
              <div class="field-value">{refs_html or "N/A"}</div>
            </div>
          </div>
        </div>"""

        findings_section = f"<h2>Findings ({sev.total})</h2>{finding_cards}"
    else:
        findings_section = "<h2>Findings</h2><p>No findings recorded.</p>"

    # --- Methodology ---
    methodology_section = f"""
    <h2>Methodology</h2>
    <p class="field-value">{_esc(meta.methodology)}</p>"""

    # --- Scan History ---
    if ctx.scan_records:
        scan_rows = ""
        for s in ctx.scan_records:
            scan_rows += f"""
        <tr>
          <td>{_esc(s.scan_id)}</td>
          <td>{_esc(s.target)}</td>
          <td>{_esc(s.scan_type)}</td>
          <td>{_esc(s.started_at)}</td>
          <td>{_esc(s.status)}</td>
          <td>{s.num_findings}</td>
        </tr>"""
        scan_section = f"""
    <h2>Scan History</h2>
    <table class="scan-table">
      <thead>
        <tr>
          <th>Scan ID</th><th>Target</th><th>Type</th>
          <th>Started</th><th>Status</th><th>Findings</th>
        </tr>
      </thead>
      <tbody>{scan_rows}</tbody>
    </table>"""
    else:
        scan_section = "<h2>Scan History</h2><p>No scan records found.</p>"

    # --- Assemble ---
    body = (
        meta_grid
        + exec_section
        + sev_section
        + findings_section
        + methodology_section
        + scan_section
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{_esc(meta.title)}</title>
  {_CSS}
</head>
<body>
{header}
<main>
{body}
</main>
<footer>
  <p>Generated by StrixSec v{_esc(meta.strixsec_version)} &mdash; {_esc(meta.generated_at)}</p>
</footer>
</body>
</html>
"""
