"""
Markdown Report Renderer for StrixSec.
"""

from __future__ import annotations

from strixsec.reporting.models import ReportContext


def render_markdown(ctx: ReportContext) -> str:
    """Render a GFM-compatible Markdown report from a ReportContext.

    Args:
        ctx: Assembled ReportContext from ReportBuilder.

    Returns:
        Complete Markdown document as a string.
    """
    meta = ctx.metadata
    sev = ctx.severity_summary
    lines: list[str] = []

    # --- Title & Metadata ---
    lines += [
        f"# {meta.title}",
        "",
        f"**Generated by:** StrixSec v{meta.strixsec_version}  ",
        f"**Generated at:** {meta.generated_at}  ",
        f"**Total Findings:** {sev.total}  ",
        "",
        "---",
        "",
    ]

    # --- Scope & Assets ---
    lines += ["## Scope", ""]
    if meta.scope:
        for entry in meta.scope:
            lines.append(f"- `{entry}`")
    else:
        lines.append("_No scope entries defined._")
    lines += [""]

    lines += ["## Assets Assessed", ""]
    if meta.assets:
        for asset in meta.assets:
            lines.append(f"- `{asset}`")
    else:
        lines.append("_No assets recorded._")
    lines += ["", "---", ""]

    # --- Executive Summary ---
    lines += ["## Executive Summary", "", ctx.executive_summary, "", "---", ""]

    # --- Severity Summary Table ---
    lines += [
        "## Severity Summary",
        "",
        "| Severity | Count |",
        "|---|---|",
        f"| 🔴 CRITICAL | {sev.critical} |",
        f"| 🟠 HIGH | {sev.high} |",
        f"| 🟡 MEDIUM | {sev.medium} |",
        f"| 🔵 LOW | {sev.low} |",
        f"| ⚪ INFORMATIONAL | {sev.informational} |",
        f"| **TOTAL** | **{sev.total}** |",
        "",
        "---",
        "",
    ]

    # --- Findings ---
    lines += [f"## Findings ({sev.total})", ""]

    if not ctx.findings:
        lines += ["_No findings recorded._", ""]
    else:
        for f in ctx.findings:
            lines += [
                f"### {f.id} — {f.title}",
                "",
                "| Field | Value |",
                "|---|---|",
                f"| **Category** | {f.category} |",
                f"| **Severity** | {f.severity} |",
                f"| **Confidence** | {f.confidence} |",
                f"| **Asset** | `{f.asset}` |",
                f"| **Status** | {f.status} |",
                "",
                "**Description:**",
                "",
                f.description,
                "",
            ]

            if f.evidence:
                lines += ["**Evidence:**", ""]
                for ev in f.evidence:
                    lines += [
                        f"- **{ev.type}** / `{ev.source}`: {ev.description}",
                        "  ```",
                        f"  {ev.sanitized_value}",
                        "  ```",
                    ]
                lines += [""]

            lines += [
                "**Impact:**",
                "",
                f.impact or "_Not specified._",
                "",
                "**Remediation:**",
                "",
                f.remediation or "_Not specified._",
                "",
            ]

            if f.references:
                lines += ["**References:**", ""]
                for ref in f.references:
                    lines.append(f"- {ref}")
                lines += [""]

            lines += ["---", ""]

    # --- Methodology ---
    lines += ["## Methodology", "", meta.methodology, "", "---", ""]

    # --- Scan History ---
    lines += ["## Scan History", ""]
    if ctx.scan_records:
        lines += [
            "| Scan ID | Target | Type | Started | Status | Findings |",
            "|---|---|---|---|---|---|",
        ]
        for s in ctx.scan_records:
            lines.append(
                f"| `{s.scan_id}` | `{s.target}` | {s.scan_type} "
                f"| {s.started_at} | {s.status} | {s.num_findings} |"
            )
    else:
        lines.append("_No scan records found._")

    lines += ["", "---", "", f"_Report generated by StrixSec v{meta.strixsec_version}_"]

    return "\n".join(lines) + "\n"
